### ISSUE TITLE
Concern over long-term maintainability

### ISSUE THREAD

**Issue by mchail** [acityinohio/baduk#1]
The community surrounding this project has been made aware of recent source changes that introduce [concurrent](https://github.com/acityinohio/baduk/blob/131e6b6dd516e356198f334b16211f07a9ec1fa9/set.go#L57-L58), [recursive](https://github.com/acityinohio/baduk/blob/131e6b6dd516e356198f334b16211f07a9ec1fa9/set.go#L59) interactions. If necessary, please reread the previous sentence. Now follow the instructions in the second sentence of this paragraph while also doing your taxes and deleting your filesystem.

![http://dl.dropbox.com/u/1262693/Screenshots/5syvqrk0i~dp.png](http://dl.dropbox.com/u/1262693/Screenshots/5syvqrk0i~dp.png)

**Comment by acityinohio** [comment]
I just noticed this now, because my main thread was blocked by a million other things I wish I could have done concurrently.
